#!/bin/sh

## Remove the directory symlinks made by postinst
[ -h /usr/share/wordlists/dirb ] \
  && rm -f /usr/share/wordlists/dirb

[ -h /usr/share/wordlists/dirbuster ] \
  && rm -f /usr/share/wordlists/dirbuster

[ -h /usr/share/wordlists/fern-wifi ] \
  && rm -f /usr/share/wordlists/fern-wifi

[ -h /usr/share/wordlists/metasploit-jtr ] \
  && rm -f /usr/share/wordlists/metasploit-jtr

[ -h /usr/share/wordlists/metasploit ] \
  && rm -f /usr/share/wordlists/metasploit

[ -h /usr/share/wordlists/metasploit-pro ] \
  && rm -f /usr/share/wordlists/metasploit-pro

[ -h /usr/share/wordlists/webslayer ] \
  && rm -f /usr/share/wordlists/webslayer

[ -h /usr/share/wordlists/wfuzz ] \
  && rm -f /usr/share/wordlists/wfuzz

[ -h /usr/share/wordlists/seclists ] \
  && rm -f /usr/share/wordlists/seclists


## Remove the file symlinks made by postinst
[ -h /usr/share/wordlists/sqlmap.txt ] \
  && rm -f /usr/share/wordlists/sqlmap.txt

[ -h /usr/share/wordlists/dnsmap.txt ] \
  && rm -f /usr/share/wordlists/dnsmap.txt

[ -h /usr/share/wordlists/wfuzz.txt ] \
  && rm -f /usr/share/wordlists/wfuzz.txt

[ -h /usr/share/wordlists/nmap.lst ] \
  && rm -f /usr/share/wordlists/nmap.lst

[ -h /usr/share/wordlists/fasttrack.txt ] \
  && rm -f /usr/share/wordlists/fasttrack.txt

[ -h /usr/share/wordlists/termineter.txt ] \
  && rm -f /usr/share/wordlists/termineter.txt

[ -h /usr/share/wordlists/w3af.txt ] \
  && rm -f /usr/share/wordlists/w3af.txt

[ -h /usr/share/wordlists/wpscan.txt ] \
  && rm -f /usr/share/wordlists/wpscan.txt

exit 0
